// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsskwaQhfV9DTZw23fIK4QH8_iOjVvXBI',
    appId: '1:263339473458:android:dddea63d068b978439da2b',
    messagingSenderId: '263339473458',
    projectId: 'two-beer-313814',
    storageBucket: 'two-beer-313814.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0BprKg1tvet_w0qTCLkDuPaOGBqX7a_Y',
    appId: '1:263339473458:ios:db5cd6e99a6f2fcb39da2b',
    messagingSenderId: '263339473458',
    projectId: 'two-beer-313814',
    storageBucket: 'two-beer-313814.appspot.com',
    iosClientId: '263339473458-kf6cvlc8obs16dp4tkaujctoplo4vho5.apps.googleusercontent.com',
    iosBundleId: 'net.gustavoborges.twoBeer',
  );
}
